2009-06-22  Basile Starynkevitch  <basile@starynkevitch.net> 	* basilys.c (struct ppbasilysflushdata_st): removed. 	(meltppbuffer, meltppbufsiz, meltppfile, meltppfilename): added 	static variables. 	(open_meltpp_file, close_meltpp_file): added new functions. 	(basilysgc_ppstrbuf_gimple) renamed as (basilysgc_ppout_gimple) 	using above meltpp stuff. 	(basilysgc_ppstrbuf_gimpleseq) renamed 	as (basilysgc_ppout_gimpleseq) using above meltpp stuff. 	(basilysgc_ppstrbuf_tree) renamed as (basilysgc_ppout_tree) using 	above meltpp stuff. 	(basilysgc_ppstrbuf_basicblock) renamed 	as (basilysgc_ppout_basicblock) using above meltpp stuff. 	(basilysgc_ppstrbuf_mpz) renamed as (basilysgc_ppout_mpz) using 	above meltpp stuff. 	(basilysgc_ppstrbuf_mixbigint) renamed 	as (basilysgc_ppout_mixbigint) using above meltpp stuff. 	* basilys.h (basilysgc_ppstrbuf_gimple) 	(basilysgc_ppstrbuf_gimple_seq, basilysgc_ppstrbuf_tree) 	(basilysgc_ppstrbuf_basicblock, basilysgc_ppstrbuf_mpz) 	(basilysgc_ppstrbuf_mixbigint): renamed and provided as macros. 	(basilysgc_ppout_gimple) 	(basilysgc_ppout_gimple_seq, basilysgc_ppout_tree) 	(basilysgc_ppout_basicblock, basilysgc_ppout_mpz) 	(basilysgc_ppout_mixbigint): added. 	* pretty-print.c: reverted to trunk. 	* pretty-print.h: reverted to trunk. 	* gimple-pretty-print.c: reverted to trunk. 	* configure: regenerated. 	* configure.ac: testing for open_memstream. 	* cfg.c: reverted to trunk.
git-svn-id: svn+ssh://gcc.gnu.org/svn/gcc/branches/melt-branch@148805 138bc75d-0d04-0410-961f-82ee72b054a4

diff --git a/gcc/configure b/gcc/configure
--- a/gcc/configure
+++ b/gcc/configure
@@ -7509,6 +7509,81 @@ echo '%!%' after GDBM LIBS= $LIBS  CFLAGS= $CFLAGS
 
 ## Compiler probe support remove in svn rev 148272
 
+
+### check for open_memstream, a GNU libc extension useful to MELT,
+### since it opens a FILE* outputing to malloc-ed memory
+have_open_memstream=no
+echo "$as_me:$LINENO: checking for open_memstream" >&5
+echo $ECHO_N "checking for open_memstream... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#define _GNU_SOURCE
+#include <stdio.h>
+#include <stdlib.h>
+int
+main ()
+{
+
+  char* mem = NULL;
+  size_t sz = 0;
+  FILE* f = open_memstream(&mem, &sz);
+  fprintf (f, "hello argc=%d argv1=%s", argc, (argc>1)?argv[1]:"");
+  fflush (f);
+  printf ("mem=%s sz=%d\n", mem, (int) sz);
+  free(mem);
+  return 0;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6; have_open_memstream=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; have_open_memstream=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+if test "$have_open_memstream" = "yes" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPEN_MEMSTREAM 1
+_ACEOF
+
+fi
+
 # ------------------------
 # Basilys/MELT support (middle-end lisp translator)
 # ------------------------
@@ -14915,13 +14990,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:14918: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:14993: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:14921: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:14996: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:14924: output\"" >&5)
+  (eval echo "\"\$as_me:14999: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -16078,7 +16153,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 16081 "configure"' > conftest.$ac_ext
+  echo '#line 16156 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -17377,11 +17452,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17380: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17455: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17384: \$? = $ac_status" >&5
+   echo "$as_me:17459: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17716,11 +17791,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17719: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17794: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17723: \$? = $ac_status" >&5
+   echo "$as_me:17798: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17821,11 +17896,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17824: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17899: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17828: \$? = $ac_status" >&5
+   echo "$as_me:17903: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17876,11 +17951,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17879: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17954: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17883: \$? = $ac_status" >&5
+   echo "$as_me:17958: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20688,7 +20763,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 20691 "configure"
+#line 20766 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20784,7 +20859,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 20787 "configure"
+#line 20862 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
